DROP TABLE IF EXISTS `q3tweets`;

CREATE TABLE `q3tweets` (
`userid` BIGINT NOT NULL PRIMARY KEY,
`retweetids` TEXT NOT NULL
);

LOAD DATA LOCAL INFILE 'all2' INTO TABLE q3tweets 
FIELDS TERMINATED BY '\t' 
LINES TERMINATED BY 'shit\n';