DROP TABLE IF EXISTS `q5tweets`;

CREATE TABLE `q5tweets` (
`userid` BIGINT NOT NULL PRIMARY KEY,
`score1` INT NOT NULL,
`score2` INT NOT NULL,
`score3` INT NOT NULL
);

LOAD DATA LOCAL INFILE 'all' INTO TABLE q5tweets 
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';